### PR TITLE
FixedMallocPool fixes for Windows

### LINKED ISSUE #729: Use-after-free in FixedMallocPool on Windows
**Describe the bug**

Several tests are failing on Windows due to a use-after-free in `util::FixedMallocPool`.

The use-after-free can occur when a `util::FixedMallocPool` object is copy-constructed from another `util::FixedMallocPool` object. This copy construction is shallow, producing two identical `util::FixedMallocPool::m_pool` vectors of `util::FixedMallocPool::Pool` objects that point to the same allocated data. This data is freed when one of the `util::FixedMallocPool` objects is destroyed, leaving the other object with a dangling pointer.

The copy construction occurs on Windows in `strategy::QuickPool`, where `util::FixedMallocPool` is used to implement `strategy::QuickPool::pool_allocator`, which is used as an allocator for an STL container. Microsoft's STL requires that the allocator is copy-constructable, hence the extra code:

https://github.com/LLNL/Umpire/blob/3966120a693c91ea7076653477414139044206fc/src/umpire/strategy/QuickPool.hpp#L116-L120

**To Reproduce**

Please see the "compilers" section below for the CMake and compiler details. The short version is:
```
>cmake ..\Umpire
>cmake --build .
>.\bin\Debug\strategy_tests
```

The tail of the GTest output:
```
[==========] 111 tests from 19 test suites ran. (1488 ms total)
[  PASSED  ] 103 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] StrategyTest/6.AllocateDeallocateBig, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] StrategyTest/6.MultipleAllocateDeallocate, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] StrategyTest/6.GetSize, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] StrategyTest/6.get_allocator_records, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] StrategyTest/6.getCurrentSize, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] StrategyTest/6.getActualSize, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] ReleaseTest/2.ReleaseCheck, where TypeParam = class umpire::strategy::QuickPool
[  FAILED  ] MixedPool.Host
```

**Expected behavior**

No use-after-free.

**Compilers & Libraries**

Configure:
```
cmake ^
-DCMAKE_CXX_STANDARD=17 ^
-DCMAKE_INSTALL_PREFIX=.\_install ^
-DBLT_CXX_STD= ^
-DUMPIRE_ENABLE_C=On ^
-DUMPIRE_ENABLE_FILESYSTEM=On ^
-DUMPIRE_ENABLE_FILE_RESOURCE=Off ^
..\Umpire
```

Compiler:
- Visual Studio 16 2019
- Windows SDK version 10.0.19041.0
- MSVC 19.27.29111.0

**Additional context**

Umpire version: 3966120a693c91ea7076653477414139044206fc

A simple fix is to delete `util::FixedMallocPool`'s copy constructor, but doing that will require a Windows-specific implementation for `strategy::QuickPool::pool_allocator`. Would that be OK?

### PR DESCRIPTION
**Pull request by davidbeckingsale**
Local copy of #741 
Closes #729

### CODE REVIEW

File: src/umpire/util/FixedMallocPool.hpp [hunk 1]
```diff
@@ -42,6 +53,7 @@ class FixedMallocPool {
 
   void newPool();
   void* allocInPool(Pool& p) noexcept;
+  void* allocate_impl(std::size_t bytes);
```
Comment (mcfadden8) [inline src/umpire/util/FixedMallocPool.hpp:56]: What is the purpose for `allocate_impl` instead of `allocate`?  It seems different from the rest of the patterns we use

Comment (mcfadden8) [inline src/umpire/util/FixedMallocPool.hpp:58]: What is the purpose for `allocate_impl` instead of `allocate`?  It seems different from the rest of the patterns we use.  If there is a reason for the difference, a comment would be helpful.

Comment (davidbeckingsale) [reply src/umpire/util/FixedMallocPool.hpp:58]: @degrbg answered this on the original PR #741 - it was to avoid repeated assert statement in the recursive allocate call.

Comment (mcfadden8) [reply src/umpire/util/FixedMallocPool.hpp:58]: Thanks, please add a comment describing this so that someone isn't tempted to switch it back in the future.

**Review by mcfadden8 — APPROVED** [review]
